import StellarSdk from 'stellar-sdk';

// GC6YHEOM2IKPZMWK73XZA5SQ2H5LJTNVIZDZAS2JBPLIA2VBEW3SRZBN
// SANZ6RQMJQDGC2TJN4RPBF2S2MKJ5Z2AHPEOBNEEFDLJSDCILYP5MFVR

const { Keypair } = StellarSdk;

const issuerKeyPair = Keypair.fromSecret("SANZ6RQMJQDGC2TJN4RPBF2S2MKJ5Z2AHPEOBNEEFDLJSDCILYP5MFVR");

export default issuerKeyPair;